### PR TITLE
Swift Package Manager support

### PR DESCRIPTION
**Pull request by defagos**
Hi,

First of all thank you very much for Aiolos. It is really well-crafted component with a great attention to detail.

This PR adds support for Swift Package Manager. I simply reused the existing directory structure as is and provided the required source location in the package manifest. The integration documentation has been updated accordingly.

The Swift tools version has been set to 5.0 which should be enough for compatibility with older Xcode versions.

Thanks in advance for having a look at this PR!

Best regards.

### CODE REVIEW

**Review by jalalcoox — APPROVED** [review]

**Review by myell0w — APPROVED** [review]
Thank you for the kind words and adding support for SPM 🙏🏻

**Comment by defagos** [comment]
Thank you very much for having merged my PR so fast. Really appreciated!

**Comment by pyby** [comment]
Thank you @myell0w. The SPM support works as expected on Aiolos `main` branch in our project.
Next, we could use the last commit, or the next release tag, if any.
Thank you again for your review. 😌

**Comment by myell0w** [comment]
Happy to hear that @pyby and thans again for contributing this @defagos 🙏

**Pull request merged**
